@token=1578|13rNbZ6MODgDvBqvWEU5MrqBUemgtp5auz4TzxXx
### login
POST  https://demo.limerickbd.com/backend/public/api/login HTTP/1.1
content-type: application/json

{
    "email": "admin@gmail.com",
    "password": "12345678"
}


### get all product
GET https://demo.limerickbd.com/backend/public/api/fg-with-stock HTTP/1.1
Authorization : Bearer {{token}}

### 
POST https://demo.limerickbd.com/backend/public/api/logout HTTP/1.1
Authorization : Bearer {{token}}

